---
runtime: python311  # Especifica la versión de Python

# Configuración de la instancia
instance_class: F2  # Clase de instancia opcional, ajusta según tus necesidades

# Handlers (manejo de rutas)
handlers:
  - url: /.*  # Cualquier URL
    script: auto  # Ejecuta automáticamente el script adecuado

# Entrypoint de Docker
entrypoint: gunicorn -b :$PORT app:app
